name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - dev
    paths:
      - 'platform/adf/**'
      - '.github/workflows/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        if: github.event_name == 'push'
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Build ADF Artifact
        if: github.event_name == 'push'
        run: |
          npm install -g @microsoft/azure-data-factory-utilities
          npm exec -- adf-publish src/adf --output-path adf-output

      - name: Upload ADF Artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: adf-arm-template
          path: adf-output
