name: CI

on:
  push:
    branches:
      - main
      - dev
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - run: echo "Hello, world!"
    
